using System;
using System.Collections.Generic;
using UnityEngine;

namespace LTW.UnityClient.Simulation
{
    [CreateAssetMenu(fileName = "TowerVisualLibrary", menuName = "Line Wars/Tower Visual Library")]
    public sealed class TowerVisualLibrary : ScriptableObject
    {
        [SerializeField] private TowerVisualProfile[] profiles = Array.Empty<TowerVisualProfile>();

        public IReadOnlyList<TowerVisualProfile> Profiles => profiles ?? Array.Empty<TowerVisualProfile>();

        public TowerVisualProfile FindProfile(string towerId)
        {
            if (string.IsNullOrWhiteSpace(towerId))
            {
                return null;
            }

            var availableProfiles = Profiles;
            for (var index = 0; index < availableProfiles.Count; index++)
            {
                var profile = availableProfiles[index];
                if (profile != null && profile.Matches(towerId))
                {
                    return profile;
                }
            }

            return null;
        }
    }

    [Serializable]
    public sealed class TowerVisualProfile
    {
        [SerializeField] private string towerId = string.Empty;
        [SerializeField] private TowerVisualRole role = TowerVisualRole.Arrow;
        [SerializeField] private GameObject prefab = null;
        [SerializeField] private Vector3 scale = Vector3.zero;
        [SerializeField] private float lift = 0.12f;
        [SerializeField] private string bodyRendererPath = "Body";
        [SerializeField] private string roleMarkerRendererPath = "RoleMarker";
        [SerializeField] private string ownerTrimRendererPath = "OwnerTrim";
        [SerializeField] private string rangeHaloRendererPath = "RangeHalo";

        public string TowerId => towerId;

        public TowerVisualRole Role => role;

        public GameObject Prefab => prefab;

        public Vector3 Scale => scale;

        public bool HasScale => scale.sqrMagnitude > 0.0001f;

        public float Lift => lift;

        public string BodyRendererPath => bodyRendererPath;

        public string RoleMarkerRendererPath => roleMarkerRendererPath;

        public string OwnerTrimRendererPath => ownerTrimRendererPath;

        public string RangeHaloRendererPath => rangeHaloRendererPath;

        public bool Matches(string contentId) =>
            string.Equals(towerId, contentId, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Presentation identity of a tower. Drives idle motion, yaw locking and the head's rest
    /// heading, all of which are looked up in one place (UnityVerticalSliceRenderer's
    /// TowerMotionProfileFor).
    /// </summary>
    /// <remarks>
    /// Values are appended, never reordered: the enum is serialised by index into
    /// TowerVisualLibrary.asset, so inserting in the middle would silently repoint every existing
    /// profile at a different role.
    /// </remarks>
    public enum TowerVisualRole
    {
        Arrow = 0,
        Control = 1,
        Relay = 2,
        Pulse = 3,
        Prism = 4,

        // Foundry line.
        Gatling = 5,
        Tesla = 6,
        Foundry = 7,
        Barricade = 8,
        RepairDrone = 9,

        // Grove line.
        ElderCanopy = 10,
        Sapling = 11,
        Bloomheart = 12,
        ThornSnare = 13,
        SporeCloud = 14,

        // Roster expansion. Appended with explicit values rather than inserted into a line's
        // block: these are serialized by index into TowerVisualLibrary and every prefab that
        // references one, so renumbering an existing role would silently repoint assets.
        TwinCrescent = 15
    }

    /// <summary>
    /// Per-role presentation corrections that every view of a tower has to agree on.
    /// </summary>
    /// <remarks>
    /// Shared because there are now two places that put a tower on screen — the board renderer and
    /// the codex's preview stage — and a correction applied in one of them would mean the showcase
    /// screen and the game disagree about what a tower looks like.
    ///
    /// The natural home for a rest pose is the prefab, and this is deliberately not there. These
    /// prefabs are generated by <c>Tower3DImportPipeline</c> from raw Meshy drops, so a hand edit is
    /// discarded by the next regeneration; moving the number into that pipeline is the right
    /// permanent fix and belongs to whoever owns it, with this as the citation.
    /// </remarks>
    public static class TowerVisualTuning
    {
        /// <summary>
        /// How far off horizontal a tower's spin part rests. See
        /// <c>UnityVerticalSliceRenderer.SpinPartRestTiltDegrees</c> for the measurements behind it.
        /// </summary>
        public static float SpinPartRestTiltDegrees(TowerVisualRole role) => role switch
        {
            TowerVisualRole.Relay => RelayDishRestTiltDegrees,
            _ => 0f
        };

        /// <summary>Names of the sub-parts that spin, most specific first.</summary>
        public static readonly string[] SpinPartNames = { "Ring", "Dish", "Spire" };

        private const float RelayDishRestTiltDegrees = 40f;
    }
}
