#!/usr/bin/env python3
"""Generates every audio asset in the project, deterministically.

LAUNCH_ROADMAP P0 item 3: the game's audio was seven procedural sine beeps and zero audio
asset files. This script is the fix's foundation: it synthesizes a full cue set plus an
ambient music bed as ordinary WAV files that Unity imports like any authored asset.

Why synthesis rather than sourced audio: nothing here can license a sound library, and
committed binaries that cannot be regenerated from the repo are a defect this project has
already been bitten by (OPEN_ITEMS item 18, eleven unregenerable texture maps). Every WAV
this writes is reproducible bit-for-bit from this file — change a sound by editing its
function and re-running, never by editing a WAV.

--------------------------------------------------------------------------------------
The second pass ("sounds good, just basic"), and what it added
--------------------------------------------------------------------------------------
The first pass was dry additive synthesis: correct, coherent, and audibly generated. The
owner's verdict was exactly that, so this pass closes the three gaps that make the
difference between *synthesized* and *produced*:

- SPACE. Every cue now passes through a small Schroeder reverb, tuned per family and baked
  into the file — a tight metallic room for FOUNDRY, an airier hall for GROVE, a shimmer
  for ARCANE, a long dark tail for the stings. Dryness was the single loudest tell that a
  sound came from a generator, and baking the space costs nothing at runtime.

- ONE KEY. The music bed is D minor; the cues used to be pitched wherever convenient. Every
  tonal cue is now built from the NOTE table below — confirmations on the D tonic, victory
  on the relative major (F), the leak alarm on the in-key maximal dissonance (Bb against A).
  A soundscape that agrees with itself is most of what "designed" means.

- REAL INSTRUMENTS where the sines were thinnest. GROVE shots are Karplus-Strong plucked
  strings (a physical model — an excited delay line IS a string, so it sounds like wood
  and tension rather than an oscillator). Impacts and the foundry ring are modal synthesis:
  a bank of exponentially-decaying resonant modes, which is how struck objects actually
  behave. Ratios for metal are deliberately inharmonic.

- VARIANTS. Constant cues (shots, hits, kills, snare) now ship 2-3 takes each, generated by
  jittering synthesis parameters under per-variant seeds. The director round-robins them;
  pitch jitter alone cannot hide sample repetition in a long fight.

Mix intent, unchanged from the first pass:
  - Cues that fire constantly (shots, hits) peak low (~0.14-0.18).
  - Cues that mean money or progress (income, build) sit mid (~0.3).
  - Cues that demand attention (leak, elimination, match end) peak high (~0.5-0.75).
  - The music bed peaks ~0.3 and must stay under everything - it is a floor, not a voice.
  Reverb is renormalized back to each cue's pre-verb peak, so space never changes loudness.

Loop correctness for the music bed is constructed, not hoped for: every tonal oscillator's
frequency is quantized to a whole number of cycles per loop, so phase at the seam equals
phase at zero; the noise layer is seam-crossfaded. `--verify` checks the seam numerically
along with peaks, DC offset and edge clicks, across every variant file.
"""

from __future__ import annotations

import argparse
import math
import sys
import wave
from dataclasses import dataclass
from pathlib import Path

import numpy as np

SFX_RATE = 44100
MUSIC_RATE = 32000
REPO = Path(__file__).resolve().parents[2]
SFX_DIR = REPO / "unity/LTW.UnityClient/Assets/Resources/Audio/SFX"
MUSIC_DIR = REPO / "unity/LTW.UnityClient/Assets/Resources/Audio/Music"


def _rng_for(name: str) -> np.random.Generator:
    """Every sound VARIANT gets its own generator, seeded from its full name.

    A single shared RNG was the first version, and it made a lie of this file's editing
    promise: noise() draws from the stream in call order, so ADDING a sound shifted the
    draws for every sound generated after it. Per-name seeding makes edits isolated:
    touching one sound's function can only ever change that sound's files."""
    return np.random.default_rng(20260803 + int.from_bytes(name.encode()[:8].ljust(8, b'\0'), 'big') % 1000003)


RNG = _rng_for("default")  # rebound per variant by main() and by music_bed()


# --------------------------------------------------------------------------- the key
# D natural minor. Every tonal cue draws from this table; a frequency literal outside it
# should be either noise-adjacent (sweep endpoints, metal modes) or a deliberate exception
# with a comment. Names are note + octave.
NOTE = {
    "D1": 36.71, "D2": 73.42, "G2": 98.00, "A2": 110.00,
    "D3": 146.83, "E3": 164.81, "F3": 174.61, "G3": 196.00, "A3": 220.00, "Bb3": 233.08, "C4": 261.63,
    "D4": 293.66, "E4": 329.63, "F4": 349.23, "G4": 392.00, "A4": 440.00, "Bb4": 466.16, "C5": 523.25,
    "D5": 587.33, "E5": 659.25, "F5": 698.46, "G5": 783.99, "A5": 880.00, "Bb5": 932.33, "C6": 1046.50,
    "D6": 1174.66, "F6": 1396.91, "A6": 1760.00,
}


# --------------------------------------------------------------------------- primitives

def t(duration: float, rate: int = SFX_RATE) -> np.ndarray:
    return np.arange(int(rate * duration)) / rate


def jit(value: float, pct: float) -> float:
    """Per-variant parameter scatter. Draws from the variant's own RNG, so takes differ
    from each other and every take is individually reproducible."""
    return float(value * RNG.uniform(1 - pct, 1 + pct))


def env(x: np.ndarray, attack: float, tail: float, rate: int = SFX_RATE) -> np.ndarray:
    """Attack ramp then exponential decay. The ramp is what stops onset clicks."""
    n = len(x)
    a = max(1, int(attack * rate))
    e = np.ones(n)
    e[:a] = np.linspace(0.0, 1.0, a)
    decay = np.exp(-np.arange(n) / (tail * rate))
    return x * e * decay


def partials(base: float, spec: list[tuple[float, float]], duration: float,
             detune: float = 0.0, rate: int = SFX_RATE) -> np.ndarray:
    """A stack of (ratio, amplitude) partials; detune doubles each voice slightly apart,
    which is the whole difference between 'crystal' and 'test tone'."""
    x = t(duration, rate)
    out = np.zeros(len(x))
    for ratio, amp in spec:
        f = base * ratio
        out += amp * np.sin(2 * math.pi * f * x)
        if detune > 0:
            out += amp * 0.6 * np.sin(2 * math.pi * f * (1 + detune) * x + 0.7)
    return out


def sweep(f0: float, f1: float, duration: float, rate: int = SFX_RATE) -> np.ndarray:
    """Exponential pitch sweep - energy weapons fall, materialize cues rise."""
    x = t(duration, rate)
    k = math.log(f1 / f0)
    phase = 2 * math.pi * f0 * duration / k * (np.exp(k * x / duration) - 1)
    return np.sin(phase)


def noise(duration: float, lp_hz: float, rate: int = SFX_RATE) -> np.ndarray:
    """One-pole low-passed white noise: the body of every impact and whoosh."""
    raw = RNG.standard_normal(int(rate * duration))
    alpha = 1.0 - math.exp(-2 * math.pi * lp_hz / rate)
    out = np.empty_like(raw)
    acc = 0.0
    for i, sample in enumerate(raw):
        acc += alpha * (sample - acc)
        out[i] = acc
    return out


def pluck(freq: float, duration: float, brightness: float = 0.5, rate: int = SFX_RATE) -> np.ndarray:
    """Karplus-Strong plucked string: a noise burst circulating in a delay line with a
    damping filter. This IS a string, physically — the delay is the round trip along it,
    the filter is energy loss — which is why it sounds like wood and tension where a
    partial stack sounds like electronics. brightness 0..1 maps to how dark the pluck is."""
    n = int(rate * duration)
    period = max(2, int(rate / freq))
    line = RNG.uniform(-1, 1, period)
    # darker pluck: pre-filter the excitation burst
    for _ in range(int((1 - brightness) * 4)):
        line = 0.5 * (line + np.roll(line, 1))
    out = np.empty(n)
    damp = 0.996
    for i in range(n):
        head = line[i % period]
        nxt = line[(i + 1) % period]
        line[i % period] = damp * 0.5 * (head + nxt)
        out[i] = head
    return out


def modal(base: float, modes: list[tuple[float, float, float]], duration: float,
          rate: int = SFX_RATE) -> np.ndarray:
    """A struck object as a bank of resonant modes: (ratio, amplitude, decay_seconds) per
    mode, each an exponentially-decaying sine. This is how impacts actually ring — high
    modes die first, the fundamental lingers — and the ratio set is the material: near-
    harmonic reads as glass or crystal, inharmonic (2.76, 5.40, 8.93) as struck metal."""
    x = t(duration, rate)
    out = np.zeros(len(x))
    for ratio, amp, decay in modes:
        out += amp * np.sin(2 * math.pi * base * ratio * x) * np.exp(-x / decay)
    return out


def reverberate(x: np.ndarray, wet: float, decay: float, size: float = 1.0,
                rate: int = SFX_RATE) -> np.ndarray:
    """Schroeder reverb baked into the sample: four parallel combs (the room's echo
    density) into two series allpasses (the smearing that stops the combs fluttering).
    `decay` is roughly RT60; `size` scales the comb delays — small is a chamber, large a
    hall. The tail is appended to the buffer so the space can ring past the dry sound."""
    tail = int(rate * decay * 0.8)
    dry = np.concatenate([x, np.zeros(tail)])
    combs = np.zeros_like(dry)
    for delay_ms in (29.7, 37.1, 41.1, 43.7):
        d = max(1, int(rate * delay_ms * size / 1000))
        g = 10 ** (-3 * (d / rate) / decay)  # feedback for RT60 = decay
        buf = np.zeros_like(dry)
        for i in range(len(dry)):
            buf[i] = dry[i] + (g * buf[i - d] if i >= d else 0.0)
        combs += buf
    combs *= 0.25
    for delay_ms, g in ((5.0, 0.7), (1.7, 0.7)):
        d = max(1, int(rate * delay_ms / 1000))
        out = np.zeros_like(combs)
        for i in range(len(combs)):
            back = out[i - d] if i >= d else 0.0
            out[i] = -g * combs[i] + (combs[i - d] if i >= d else 0.0) + g * back
        combs = out
    return dry * (1 - wet) + combs * wet


def polish(x: np.ndarray, peak: float) -> np.ndarray:
    """Soft-clip, normalize to the cue's mix target, and close both edges to zero.

    tanh glues partials into one voice and guarantees no sample exceeds the target no
    matter how layers sum. The edge fades exist because an exponential decay never
    actually reaches zero — --verify caught five cues ending mid-decay, which is a click
    on every playback. A 20ms raised-cosine out and a 2ms in close every voice cleanly."""
    x = np.tanh(x * 1.5)
    m = np.max(np.abs(x))
    if m > 0:
        x = x * (peak / m)
    fade_in = min(len(x), int(0.002 * SFX_RATE))
    fade_out = min(len(x), int(0.020 * SFX_RATE))
    x[:fade_in] *= np.linspace(0.0, 1.0, fade_in)
    x[-fade_out:] *= 0.5 * (1 + np.cos(np.linspace(0, math.pi, fade_out)))
    return x


def pad_sum(voices) -> np.ndarray:
    """Mixes voices at sample offsets; a bare array means offset zero."""
    prepared = [(v, 0.0) if isinstance(v, np.ndarray) else v for v in voices]
    length = max(int(off * SFX_RATE) + len(v) for v, off in prepared)
    out = np.zeros(length)
    for v, off in prepared:
        start = int(off * SFX_RATE)
        out[start:start + len(v)] += v
    return out


# --------------------------------------------------------------------------- SFX voices
# One function per cue, pitched from NOTE. jit() calls are what vary between takes of a
# multi-variant cue; a single-variant cue may still use jit (it draws deterministically).

def tower_placed() -> np.ndarray:
    """Materialize: energy rising an octave to the tonic, settling into a D power chord."""
    rise = env(sweep(NOTE["D3"], NOTE["D4"], jit(0.16, 0.08)), 0.004, 0.06)
    settle = env(partials(NOTE["D4"], [(1, 1.0), (1.5, 0.5), (2, 0.3)], 0.28, detune=0.004), 0.01, 0.11)
    thump = env(noise(0.12, 240), 0.002, 0.035) * 0.8
    return polish(pad_sum([rise, (settle, 0.05), (thump, 0.0)]), 0.30)


def tower_sold() -> np.ndarray:
    """The build cue's mirror: the same octave walked back down, dissolving on F."""
    fall = env(sweep(NOTE["D4"], NOTE["D3"], 0.18), 0.004, 0.07)
    dissolve = env(partials(NOTE["F3"], [(1, 1.0), (2, 0.4)], 0.22, detune=0.005), 0.01, 0.08)
    return polish(pad_sum([fall, (dissolve, 0.04)]), 0.26)


def tower_upgraded() -> np.ndarray:
    """Three ascending crystal strikes up the tonic triad: D, F, A."""
    voices = []
    for i, note in enumerate(["D5", "F5", "A5"]):
        strike = env(modal(NOTE[note], [(1, 1.0, 0.10), (2.01, 0.35, 0.05), (3.0, 0.15, 0.03)], 0.30), 0.003, 0.12)
        voices.append((strike, i * 0.07))
    return polish(pad_sum(voices), 0.32)


def tier_purchased() -> np.ndarray:
    """Heavier than a single upgrade: a low tonic commit under the triad reaching the octave."""
    low = env(partials(NOTE["D3"], [(1, 1.0), (2, 0.5)], 0.5, detune=0.003), 0.005, 0.22)
    arp = [(env(partials(NOTE[n], [(1, 0.7), (3.01, 0.2)], 0.25, detune=0.005), 0.003, 0.09), 0.05 + i * 0.06)
           for i, n in enumerate(["D5", "F5", "A5", "D6"])]
    return polish(pad_sum([low] + arp), 0.34)


def creep_sent() -> np.ndarray:
    """Dispatch whoosh: filtered noise sweeping up over a low A pulse (the dominant —
    tension leaving home, unresolved on purpose)."""
    rush = env(noise(jit(0.3, 0.1), jit(900, 0.2)), 0.02, 0.12)
    ramp = np.linspace(0.4, 1.0, len(rush))
    pulse = env(partials(NOTE["A2"], [(1, 1.0), (2, 0.3)], 0.3), 0.01, 0.1)
    return polish(pad_sum([rush * ramp, pulse]), 0.28)


def tower_shot() -> np.ndarray:
    """ARCANE discharge: a falling zap, D6 down to D4. Peaks LOW - shots are the roster's
    most frequent sound by an order of magnitude."""
    zap = env(sweep(jit(NOTE["D6"], 0.06), jit(NOTE["D4"], 0.06), jit(0.06, 0.15)), 0.002, 0.02)
    snap = env(noise(0.03, 3000), 0.001, 0.008) * 0.5
    return polish(pad_sum([zap, snap]), 0.14)


def tower_shot_foundry() -> np.ndarray:
    """FOUNDRY discharge: a machined impact - modal metal ring over a low punch. The mode
    ratios are deliberately inharmonic; metal is the one material allowed out of key."""
    punch = env(sweep(jit(300, 0.1), 90, 0.07), 0.002, 0.025)
    ring = modal(jit(NOTE["A3"], 0.04), [(2.76, 0.5, 0.05), (5.40, 0.35, 0.03), (8.93, 0.2, 0.018)], 0.09)
    grit = env(noise(0.04, 1800), 0.001, 0.012) * 0.6
    return polish(pad_sum([punch, ring, grit]), 0.15)


def tower_shot_grove() -> np.ndarray:
    """GROVE discharge: a plucked string. Karplus-Strong on F3 - actual wood-and-tension
    physics, no oscillator anywhere in the tone."""
    string = env(pluck(jit(NOTE["F3"], 0.05), 0.14, brightness=jit(0.55, 0.2)), 0.001, 0.06)
    leaves = env(noise(0.05, 5200), 0.001, 0.018) * 0.35
    return polish(pad_sum([string, leaves]), 0.14)


def creep_hit() -> np.ndarray:
    """Damage tick: barely more than texture. Constant in every fight."""
    tick = env(noise(jit(0.03, 0.2), jit(2400, 0.25)), 0.001, 0.01)
    body = env(partials(NOTE["A4"], [(1, 0.6)], 0.03), 0.001, 0.012)
    return polish(pad_sum([tick, body]), 0.13)


def creep_killed() -> np.ndarray:
    """Crystal shatter as modal glass: near-harmonic high modes over a noise crack, rooted
    on the upper tonic."""
    crack = env(noise(0.08, 4200), 0.001, 0.02)
    shards = modal(jit(NOTE["D6"], 0.05),
                   [(1, 0.8, 0.06), (1.5, 0.6, 0.045), (2.01, 0.45, 0.03), (2.99, 0.3, 0.02)], 0.2)
    return polish(pad_sum([crack, (shards, 0.008)]), 0.24)


def creep_leaked() -> np.ndarray:
    """The bad sound: Bb falling onto A - the key's own maximal dissonance, kept rough.
    In-key so it belongs to the score; a semitone so it can never be mistaken for good news."""
    a = env(partials(NOTE["Bb5"], [(1, 1.0), (2.01, 0.4)], 0.22, detune=0.01), 0.004, 0.09)
    b = env(partials(NOTE["A5"], [(1, 1.0), (2.01, 0.4)], 0.3, detune=0.01), 0.004, 0.12)
    growl = env(noise(0.4, 500), 0.01, 0.18) * 0.5
    return polish(pad_sum([a, (b, 0.12), growl]), 0.50)


def income_tick() -> np.ndarray:
    """Soft coin chime on the tonic dyad D6+A6 - must be pleasant on the five-hundredth
    hearing, which is what consonance with the bed buys."""
    a = env(partials(NOTE["D6"], [(1, 1.0)], 0.09), 0.002, 0.035)
    b = env(partials(NOTE["A6"], [(1, 0.8)], 0.12), 0.002, 0.05)
    return polish(pad_sum([a, (b, 0.045)]), 0.24)


def creep_snared() -> np.ndarray:
    """Bramble catch: a woody creak, G down to D, with pluck fibers - vines snapping taut.
    Companion to the bramble decal: the ground shows where, this says when."""
    creak = env(sweep(jit(NOTE["G3"], 0.06), NOTE["D3"], jit(0.14, 0.15)), 0.006, 0.06)
    fibers = env(pluck(NOTE["D3"], 0.1, brightness=0.3), 0.002, 0.045) * 0.6
    return polish(pad_sum([creak, fibers]), 0.20)


def player_eliminated() -> np.ndarray:
    """A seat falling: deep tonic impact with dark modal ring and a long tail."""
    boom = env(sweep(NOTE["D3"], NOTE["D1"], 0.9), 0.005, 0.4)
    ring = modal(NOTE["D2"], [(1, 0.8, 0.5), (1.5, 0.4, 0.3), (2.76, 0.25, 0.15)], 1.0)
    body = env(noise(0.8, 180), 0.01, 0.3)
    return polish(pad_sum([boom, ring, body]), 0.62)


def match_won() -> np.ndarray:
    """Victory on the relative major: F-A-C-F rising - triumph that still lives inside
    the game's key rather than modulating out of it."""
    voices = [(env(partials(NOTE[n], [(1, 1.0), (2, 0.4), (4, 0.12)], 1.3, detune=0.004), 0.005, 0.5), d)
              for n, d in [("F4", 0.0), ("A4", 0.1), ("C5", 0.2), ("F5", 0.3)]]
    return polish(pad_sum(voices), 0.55)


def match_lost() -> np.ndarray:
    """Defeat walks down to the tonic and stays there: A-F-E-D over a low rumble."""
    voices = [(env(partials(NOTE[n], [(1, 1.0), (2, 0.3)], 1.4, detune=0.005), 0.008, 0.55), d)
              for n, d in [("A4", 0.0), ("F4", 0.15), ("E4", 0.3), ("D4", 0.45)]]
    rumble = env(noise(1.8, 150), 0.05, 0.8) * 0.35
    return polish(pad_sum(voices + [rumble]), 0.52)


def ui_reject() -> np.ndarray:
    """Denied: a dull double buzz on the low dominant, deliberately unmusical in timbre
    while staying in key - rejections often come in taps of three."""
    a = env(partials(NOTE["A2"], [(1, 1.0), (2.02, 0.55), (2.98, 0.3)], 0.07, detune=0.015), 0.003, 0.03)
    b = env(partials(NOTE["G2"], [(1, 1.0), (2.02, 0.55)], 0.09, detune=0.015), 0.003, 0.04)
    return polish(pad_sum([a, (b, 0.085)]), 0.22)


# --------------------------------------------------------------------------- registry

@dataclass(frozen=True)
class Sound:
    """A cue: its synthesis function, how many takes to generate, and its baked space.

    Space is (wet, decay_seconds, size). Families share rooms on purpose - FOUNDRY cues in
    a tight metallic chamber, GROVE in an airier hall, ARCANE with a shimmering mid room,
    stings in a long dark hall - so the mix sounds like one place per family rather than
    seventeen unrelated boxes."""
    fn: object
    variants: int = 1
    space: tuple[float, float, float] | None = None


ROOM_ARCANE = (0.22, 0.5, 0.9)
ROOM_FOUNDRY = (0.18, 0.3, 0.6)
ROOM_GROVE = (0.26, 0.7, 1.2)
ROOM_STING = (0.32, 1.6, 1.5)
ROOM_UI = (0.10, 0.2, 0.5)

SFX = {
    "tower_placed": Sound(tower_placed, variants=2, space=ROOM_ARCANE),
    "tower_sold": Sound(tower_sold, space=ROOM_ARCANE),
    "tower_upgraded": Sound(tower_upgraded, space=ROOM_ARCANE),
    "tier_purchased": Sound(tier_purchased, space=ROOM_ARCANE),
    "creep_sent": Sound(creep_sent, variants=2, space=ROOM_ARCANE),
    "tower_shot": Sound(tower_shot, variants=3, space=ROOM_ARCANE),
    "tower_shot_foundry": Sound(tower_shot_foundry, variants=3, space=ROOM_FOUNDRY),
    "tower_shot_grove": Sound(tower_shot_grove, variants=3, space=ROOM_GROVE),
    "creep_hit": Sound(creep_hit, variants=3, space=ROOM_FOUNDRY),
    "creep_killed": Sound(creep_killed, variants=3, space=ROOM_ARCANE),
    "creep_leaked": Sound(creep_leaked, space=ROOM_STING),
    "income_tick": Sound(income_tick, space=ROOM_UI),
    "creep_snared": Sound(creep_snared, variants=2, space=ROOM_GROVE),
    "player_eliminated": Sound(player_eliminated, space=ROOM_STING),
    "match_won": Sound(match_won, space=ROOM_STING),
    "match_lost": Sound(match_lost, space=ROOM_STING),
    "ui_reject": Sound(ui_reject, space=ROOM_UI),
}


def variant_names(name: str, sound: Sound) -> list[str]:
    """`name.wav` for singles, `name_v1..vN.wav` for multi-take cues."""
    return [name] if sound.variants == 1 else [f"{name}_v{i + 1}" for i in range(sound.variants)]


def render(name: str, variant: str, sound: Sound) -> np.ndarray:
    """One take: rebind the RNG for the variant, synthesize, bake the room, restore peak.

    Reverb runs AFTER polish and is renormalized to the polished peak, then edge-faded
    again (the tail extends the buffer past the original fade). Space must never change a
    cue's loudness - the mix policy lives in each function's polish() call, nowhere else."""
    global RNG
    RNG = _rng_for(variant)
    data = sound.fn()
    if sound.space is not None:
        peak = float(np.max(np.abs(data)))
        wet, decay, size = sound.space
        data = reverberate(data, wet, decay, size)
        m = float(np.max(np.abs(data)))
        if m > 0:
            data *= peak / m
        fade_out = min(len(data), int(0.020 * SFX_RATE))
        data[-fade_out:] *= 0.5 * (1 + np.cos(np.linspace(0, math.pi, fade_out)))
    return data


# --------------------------------------------------------------------------- music bed

MUSIC_SECONDS = 48.0
XFADE_SECONDS = 2.0


def loop_quantize(freq: float) -> float:
    """Nearest frequency completing whole cycles per loop, so the seam is phase-exact."""
    return round(freq * MUSIC_SECONDS) / MUSIC_SECONDS


def music_bed() -> np.ndarray:
    """48-second dark ambient bed in D minor. Four chords, twelve seconds each, every
    oscillator loop-quantized; only the air layer needs a seam crossfade.

    Deliberately event-free: no percussion, no melody. The game's own cues are the melody -
    this bed exists so silence between them stops sounding like a broken build.
    """
    global RNG
    RNG = _rng_for("music_bed")
    n = int(MUSIC_RATE * MUSIC_SECONDS)
    x = np.arange(n) / MUSIC_RATE

    # Dm(add9) -> Bbmaj7 -> F(add9) -> Csus2, as note frequencies.
    chords = [
        [146.83, 220.0, 293.66, 329.63],
        [116.54, 174.61, 220.0, 261.63],
        [174.61, 220.0, 261.63, 392.0],
        [130.81, 196.0, 261.63, 293.66],
    ]
    seg = n // 4
    fade = int(MUSIC_RATE * 3.0)

    bed = np.zeros(n)
    for index, chord in enumerate(chords):
        gain = np.zeros(n)
        start = index * seg
        gain[start:start + seg] = 1.0
        ramp = np.linspace(0, 1, fade)
        gain[start:start + fade] = np.minimum(gain[start:start + fade], ramp)
        tail = np.arange(fade)
        gain[(start + seg - fade + tail) % n] = np.minimum(gain[(start + seg - fade + tail) % n], 1 - ramp)
        for voice, freq in enumerate(chord):
            f = loop_quantize(freq)
            lfo = 0.85 + 0.15 * np.sin(2 * math.pi * loop_quantize(1 / (9 + 2 * voice)) * x + voice)
            for mult, amp in [(1, 1.0), (2, 0.28), (0.5, 0.4 if voice == 0 else 0.0)]:
                bed += gain * lfo * amp * 0.10 * np.sin(2 * math.pi * f * mult * x + voice * 1.3)

    bed += 0.16 * np.sin(2 * math.pi * loop_quantize(36.71) * x) * (0.8 + 0.2 * np.sin(2 * math.pi * loop_quantize(1 / 19) * x))

    air = noise(MUSIC_SECONDS + XFADE_SECONDS, 800, MUSIC_RATE) * 0.05
    xn = int(MUSIC_RATE * XFADE_SECONDS)
    w = np.sin(np.linspace(0, math.pi / 2, xn)) ** 2
    looped_air = air[:n].copy()
    looped_air[:xn] = air[:xn] * w + air[n:n + xn] * (1 - w)
    bed += looped_air

    bed = np.tanh(bed * 1.2)
    bed *= 0.30 / np.max(np.abs(bed))

    delay = int(MUSIC_RATE * 0.011)
    left = bed
    right = np.roll(bed, delay)
    return np.stack([left, right], axis=1)


# --------------------------------------------------------------------------- output

def write_wav(path: Path, data: np.ndarray, rate: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    pcm = (np.clip(data, -1, 1) * 32767).astype("<i2")
    channels = 1 if pcm.ndim == 1 else pcm.shape[1]
    with wave.open(str(path), "wb") as f:
        f.setnchannels(channels)
        f.setsampwidth(2)
        f.setframerate(rate)
        f.writeframes(pcm.tobytes())


def all_expected_files() -> list[str]:
    return [variant for name, sound in SFX.items() for variant in variant_names(name, sound)]


def verify() -> int:
    failures = []
    for variant in all_expected_files():
        path = SFX_DIR / f"{variant}.wav"
        if not path.exists():
            failures.append(f"{variant}: missing")
            continue
        with wave.open(str(path)) as f:
            raw = np.frombuffer(f.readframes(f.getnframes()), dtype="<i2") / 32767.0
        peak, dc = np.max(np.abs(raw)), abs(float(np.mean(raw)))
        if not 0.05 <= peak <= 0.8:
            failures.append(f"{variant}: peak {peak:.3f} outside mix policy")
        if dc > 0.01:
            failures.append(f"{variant}: DC offset {dc:.4f}")
        if abs(raw[0]) > 0.02 or abs(raw[-1]) > 0.02:
            failures.append(f"{variant}: does not start/end near zero (click)")

    path = MUSIC_DIR / "music_bed_loop.wav"
    if path.exists():
        with wave.open(str(path)) as f:
            raw = np.frombuffer(f.readframes(f.getnframes()), dtype="<i2").reshape(-1, 2) / 32767.0
        seam = float(np.max(np.abs(raw[0] - raw[-1])))
        step = float(np.max(np.abs(np.diff(raw[:, 0]))))
        if seam > step * 2:
            failures.append(f"music: seam discontinuity {seam:.4f} exceeds 2x max in-loop step {step:.4f}")
    else:
        failures.append("music: missing")

    for line in failures:
        print(f"FAIL  {line}")
    print(f"{'FAILED' if failures else 'OK'}: {len(all_expected_files())} sfx files + music checked, {len(failures)} problem(s)")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true", help="check existing files instead of writing")
    args = parser.parse_args()
    if args.verify:
        return verify()

    for name, sound in SFX.items():
        for variant in variant_names(name, sound):
            data = render(name, variant, sound)
            write_wav(SFX_DIR / f"{variant}.wav", data, SFX_RATE)
            print(f"wrote {variant}.wav  ({len(data) / SFX_RATE:.2f}s, peak {np.max(np.abs(data)):.2f})")
    music = music_bed()
    write_wav(MUSIC_DIR / "music_bed_loop.wav", music, MUSIC_RATE)
    print(f"wrote music_bed_loop.wav  ({MUSIC_SECONDS:.0f}s stereo, "
          f"{(MUSIC_DIR / 'music_bed_loop.wav').stat().st_size / 1e6:.1f} MB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
